### PR TITLE
Add GitHub actions

### PR DESCRIPTION
**Pull request by gwarf**

### CODE REVIEW

**Comment by gwarf** [comment]
It still needs to get the "Test" from the travis file be ported, but I'm currently stopping at the crontab dependency for CentOS 9.

**Comment by gwarf** [comment]
I've dropped some python 3 stuff like six and imports, but not touched/cleaned the code where it may be needed

**Review by enolfc — APPROVED** [review]
Nice! Go for it

**Comment by gwarf** [comment]
Thanks, but this PR in my fork was only to test the actions ;)
Can you appove/review here: https://github.com/EGI-Federation/glite-info-update-endpoints/pull/33
Thanks!

**Pull request closed without merging**
